In [36]:
import numpy as np
from tqdm import tqdm

### 1.  Elabora las funciones siguientes en Python:

a)

In [98]:
def producto_escalar(x,y):
    suma=0
    if len(x)==len(y):
        for i in range(len(x)):
            suma+=x[i]*y[i]
    else:
        print('Las dimensión n no es igual')
    return suma

In [99]:
#Ejemplo
producto_escalar([2,-1,0],[-3,-2,1])

-4

b)

In [68]:
def ortogonal(x,y):
    if producto_escalar(x,y)==0:
        return True
    else:
        return False

In [78]:
#Ejemplo
ortogonal([1,1],[-1,1])

True

### 2.  Realiza programas en Python que calculen lo siguiente:

a)

In [81]:
#Norma euclídia
def norma_euclidia(v):
    suma=0
    for i in range(len(v)):
        suma+=v[i]**2
    
    return np.sqrt(suma)

In [83]:
#Ejemplo
norma_euclidia([1,1])

1.4142135623730951

In [84]:
#Norma 1
def norma_1(v):
    suma=0
    for i in range(len(v)):
        suma+=abs(v[i])
    
    return suma

In [85]:
#Ejemplo
norma_1([1,1])

2

In [86]:
#Norma del máximo
def norma_del_maximo(v):
    return max(v)

In [87]:
#Ejemplo
norma_del_maximo([2,4,5])

5

b)

In [117]:
def projeccion_a_sobre_b(a,b):
    return (producto_escalar(a,b)/producto_escalar(b,b))*b

In [120]:
#Ejemplo
u=np.array([2,2])
v=np.array([0,4])
projeccion_a_sobre_b(u,v)

array([0., 2.])

In [121]:
def ortogonal_a_sobre_b(a,b):
    return a-projeccion_a_sobre_b(a,b)

In [123]:
#Ejemplo
u=np.array([2,2])
v=np.array([0,4])
ortogonal_a_sobre_b(u,v)

array([2., 0.])

In [132]:
u=np.random.rand(7)
v=np.random.rand(7)
producto_escalar(projeccion_a_sobre_b(u,v),ortogonal_a_sobre_b(u,v))

-8.673617379884035e-19

Vemos como el resultado es muy próximo a 0.

### 3.  Implementa en Python las funciones siguientes

a)

In [133]:
def escalar_por_matriz(escalar,matriz):
    return escalar*matriz

In [137]:
matriz = np.random.randint((10), size=(3,3))
escalar = 2
print(matriz)
escalar_por_matriz(escalar,matriz)

[[7 1 7]
 [9 9 4]
 [8 8 8]]


array([[14,  2, 14],
       [18, 18,  8],
       [16, 16, 16]])

b)

In [141]:
def suma_matrices(A,B):
    if A.shape == B.shape:
        return A+B
    else:
        print('Las dimensiones de A y B no son compatibles para efectuar la suma')

In [179]:
#Ejemplo
A = np.random.randint((10), size=(3,3))
B = np.random.randint((10), size=(3,3))
print(A)
print(B)
suma_matrices(A,B)

[[3 4 7]
 [7 9 9]
 [4 3 8]]
[[1 4 9]
 [4 9 6]
 [7 7 6]]


array([[ 4,  8, 16],
       [11, 18, 15],
       [11, 10, 14]])

c)

In [52]:
def producto_dos_matrices(A,B):
    if A.shape[1] == B.shape[0]:
        C = np.zeros((A.shape[0],B.shape[1]))
        for s in tqdm(range (A.shape[0])):
            for i in range (C.shape[0]):
                for j in range (C.shape[1]):
                    C[i][j]+=A[i][s]*B[s][j]
    else:
        print('Las dimensiones de A y B no son compatibles para efectuar el producto entre matrices')
    return C

In [6]:
#Ejemplo
A = np.random.randint((10), size=(2,2))
B = np.random.randint((10), size=(2,2))
print(A)
print(B)
C = producto_dos_matrices(A,B)
print(C)

[[7 3]
 [8 3]]
[[6 7]
 [1 5]]
[[45. 64.]
 [51. 71.]]


### 4.  Realiza  diferentes  programas  en  Python  que,  dada  una  matriz A∈Rn×n y  un  exponente k∈N, calculen Ak:

a)

In [34]:
def matriz_elevada_a_k(A,k):
    C=A
    if k==1:
        return A
    else: 
        for k in tqdm(range (k-1)):
            C = producto_dos_matrices(C,A)
        return C


In [8]:
#Ejemplo
A = np.random.randint((5), size=(2,2))
print(A)
matriz_elevada_a_k(A,3)

[[0 3]
 [3 2]]


array([[18., 39.],
       [39., 44.]])

b)

In [42]:
def matriz_elevada_diagonalizacion(A,k):
    diagonalizacion=np.linalg.eig(A)
    first=producto_dos_matrices(diagonalizacion[1],np.diag(diagonalizacion[0])**k)
    return producto_dos_matrices(first,np.linalg.inv(diagonalizacion[1]))

In [28]:
matriz_elevada_diagonalizacion(A,3)

array([[18., 39.],
       [39., 44.]])

c)

In [39]:
n=500

# Matriz aleatoria con valores comprendidos entre 0 y 1.
A=np.random.rand(n, n)

# Hago simétrica la matriz aleatoria generada anteriormente.
# Garantiza que la matriz es diagonalizable.
for i in range(0, n):
    for j in range(i+1, n):
        A[i, j]=A[j, i]

# Calculo la suma de los elementos de cada fila y me quedo con la máxima.      
maxrow=0
for i in range(0, n):
    row=0
    for j in range(0, n):
        row=row+A[i, j]
    if row>maxrow:
        maxrow=row

# Divido todas las entradas de la matriz por el valor anterior.
# Garantiza que los valores propios se encuentran entre 0 y 1.
for i in range(0, n):
    for j in range(0, n):
        A[i, j]=A[i, j]/maxrow


In [41]:
A.shape

(500, 500)

In [50]:
%%time
matriz_elevada_a_k(A,3)


100%|███████████████████████████████████████████████████████████████████████████████████| 2/2 [08:17<00:00, 247.29s/it]


Wall time: 8min 17s


array([[0.00152569, 0.00156598, 0.00144727, ..., 0.00163307, 0.00157239,
        0.00160111],
       [0.00156598, 0.0016088 , 0.00148671, ..., 0.0016753 , 0.00161849,
        0.00164547],
       [0.00144727, 0.00148671, 0.0013758 , ..., 0.00154937, 0.00149433,
        0.00152396],
       ...,
       [0.00163307, 0.0016753 , 0.00154937, ..., 0.0017464 , 0.00168224,
        0.00171338],
       [0.00157239, 0.00161849, 0.00149433, ..., 0.00168224, 0.00162599,
        0.00165286],
       [0.00160111, 0.00164547, 0.00152396, ..., 0.00171338, 0.00165286,
        0.00168104]])

In [55]:
%%time
matriz_elevada_diagonalizacion(A,3)


 13%|██████████▊                                                                      | 67/500 [00:30<03:14,  2.23it/s]


 27%|█████████████████████▌                                                          | 135/500 [01:01<02:47,  2.18it/s]


 41%|████████████████████████████████▍                                               | 203/500 [01:31<01:27,  3.39it/s]


 54%|███████████████████████████████████████████▎                                    | 271/500 [01:43<00:42,  5.44it/s]


 68%|██████████████████████████████████████████████████████▏                         | 339/500 [01:55<00:28,  5.62it/s]


 81%|█████████████████████████████████████████████████████████████████               | 407/500 [02:07<00:16,  5.64it/s]


 95%|████████████████████████████████████████████████████████████████████████████    | 475/500 [02:20<00:04,  5.60it/s]


100%|████████████████████████████████████████████████████████████████████████████████| 500/500 [02:24<00:00,  5.60it/s]

  8%|██████▊                                                                          | 42/500 [00:07<01:20,  5.71it/s]


 22%|█████████████████▌                                                              | 110/500 [00:19<01:08,  5.66it/s]


 36%|████████████████████████████▍                                                   | 178/500 [00:31<00:56,  5.68it/s]


 49%|███████████████████████████████████████▎                                        | 246/500 [00:43<00:44,  5.76it/s]


 63%|██████████████████████████████████████████████████▏                             | 314/500 [00:55<00:33,  5.62it/s]


 76%|█████████████████████████████████████████████████████████████                   | 382/500 [01:08<00:20,  5.70it/s]


 90%|████████████████████████████████████████████████████████████████████████        | 450/500 [01:20<00:08,  5.59it/s]


100%|████████████████████████████████████████████████████████████████████████████████| 500/500 [01:28<00:00,  5.63it/s]


Wall time: 3min 54s


array([[0.00152569, 0.00156598, 0.00144727, ..., 0.00163307, 0.00157239,
        0.00160111],
       [0.00156598, 0.0016088 , 0.00148671, ..., 0.0016753 , 0.00161849,
        0.00164547],
       [0.00144727, 0.00148671, 0.0013758 , ..., 0.00154937, 0.00149433,
        0.00152396],
       ...,
       [0.00163307, 0.0016753 , 0.00154937, ..., 0.0017464 , 0.00168224,
        0.00171338],
       [0.00157239, 0.00161849, 0.00149433, ..., 0.00168224, 0.00162599,
        0.00165286],
       [0.00160111, 0.00164547, 0.00152396, ..., 0.00171338, 0.00165286,
        0.00168104]])

La programación realizada no permite hacer A elevado a 10000. Tardaría mucho para calcularlo. Para demostrar pero de que la diagonalización tarda menos que el producto escalar de A k veces, lo he hecho elevando A a 3.